name: Continuous deployment

on:
  push:
    branches:
      - main
env:
  ENV_NAME: dev
  ENV_REGION: us-east-1
  BASE_DOMAIN: cesarmanriqueh.com
  NAME_PREFIX: gh-envs

jobs:
  set-env:
    runs-on: ubuntu-20.04
    outputs:
      env_name: ${{ steps.set-env.outputs.env_name }}
      region: ${{ steps.set-env.outputs.region }}
      base_domain: ${{ steps.set-env.outputs.base_domain }}
      name_prefix: ${{ steps.set-env.outputs.name_prefix }}
    steps:
      - name: Set job level environment
        id: set-env
        run: |
          echo "::set-output name=env_name::dev"
          echo "::set-output name=region::us-east-1"
          echo "::set-output name=base_domain::cesarmanriqueh.com"
          echo "::set-output name=name_prefix::gh-envs"

  deploy-base-infra:
    uses: CesarManriqueH/github-environments/.github/workflows/terraform-deployer.yml@main
    with:
      tf_state_bucket: gh-envs-tf-state
      tf_state_region: ${{ needs.set-env.outputs.region }}
      tf_workspace: base-dev
      tf_target_dir: infra/base
      tf_vars: "-var 'env_name=${{ needs.set-env.outputs.env_name }}' -var 'region=${{ needs.set-env.outputs.region }}' -var 'base_domain=${{ needs.set-env.outputs.base_domain }}'"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: set-env

  deploy-main-infra:
    uses: CesarManriqueH/github-environments/.github/workflows/terraform-deployer.yml@main
    with:
      tf_state_bucket: gh-envs-tf-states
      tf_state_region: ${{ needs.set-environment.outputs.region }}
      tf_workspace: main-dev
      tf_target_dir: infra/main
      tf_vars: " -var 'env_name=${{ needs.set-env.outputs.env_name }}' -var 'region=${{ needs.set-env.outputs.region }}' -var 'name_prefix=${{ needs.set-env.outputs.name_prefix }}' -var 'base_domain=${{ needs.set-env.outputs.base_domain }}'"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: [set-env,deploy-base-infra]

  publish-web-app:
    runs-on: ubuntu-20.04
    env:
      BUCKET_NAME: '${{ needs.set-env.outputs.name_prefix }}-${{ needs.set-env.outputs.env_name }}-web-app'
      DOMAIN: 'web-app.${{ needs.set-env.outputs.env_name }}.${{ needs.set-env.outputs.base_domain }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: .github/scripts/create-aws-creds-file.sh

      - name: Lookup CF Dist ID
        env:
          ORIGIN_DOMAIN_NAME: "${{ env.BUCKET_NAME }}.s3.amazonaws.com"
        run: |
          CF_DIST_ID=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[].{Id: Id, OriginDomainName: Origins.Items[0].DomainName}[?contains(OriginDomainName, '${ORIGIN_DOMAIN_NAME}')] | [0].Id" \
            --output text)
          echo "💡 Cloudfront Distribution found with ID: ${CF_DIST_ID}"
          echo "CF_DIST_ID=${CF_DIST_ID}" >> $GITHUB_ENV

      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        working-directory: web-app
        run: yarn

      - name: Build and export
        working-directory: web-app
        run: yarn build && yarn export

      - name: Push artifacts to s3
        working-directory: web-app
        run: |
          aws s3 sync out s3://${BUCKET_NAME}/assets --delete --cache-control "max-age=900"
          aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*"
    needs: [set-env,deploy-main-infra]

  smoke-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Confirm web page loads
        run: |
          url=https://${DOMAIN}
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null $url)
          if [[ $response != "200" ]]; then
            echo "Expected 200 from $url but got $response"
            exit 1
          fi
    needs: [set-env,publish-web-app]
