name: Continuous deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/_deployer.yml
    with:
      env_name: dev
      name_prefix: gh-envs
      aws_role_to_assume: arn:aws:iam::168846058973:role/gh-workflow-role
      aws_region: us-east-1
      base_domain: cesarmanriqueh.com
